name: (▶) Start Hotfix

on: workflow_dispatch

jobs:
  release:
    uses: sitepark/github-project-workflow/.github/workflows/pnpm-stat-hotfix.yml@main
    with:
      botName: "sitepark-bot"
      botEmail: "opensource@sitepark.com"
      nodeVersion: "24"
    secrets:
      # Sitepark-BOT personal access token
      BOT_PAT: ${{ secrets.BOT_PAT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
